module.exports = function Contract () {
  return Object.seal({
    _id: null,
    externalId: null,
    contractNumber: null,
    provider: null,
    companyId: null,
    customerId: null,
    projectId: null,
    productServiceId: null,
    categoryId: null,
    departmentId: null,
    departmentPercentage: null,
    type: null,
    municipalServiceCode: null,
    registerDate: null,
    startDate: null,
    endDate: null,
    expectedPaymentDay: null,
    grossValue: null,
    netValue: null,
    discounts: null,
    taxAmount: null,
    taxes: {
      ir: null,
      pis: null,
      cofins: null,
      csll: null,
      icms: null,
      iss: null
    },
    status: null,
    billed: null,
    billingType: null,
    step: null,
    notes: null,
    createdAt: null,
    updatedAt: null
  })
}
