module.exports = Object.seal({
  _id: undefined,
  externalId: undefined,
  contractNumber: undefined,
  provider: undefined,
  companyId: undefined,
  customerId: undefined,
  projectId: undefined,
  productServiceId: undefined,
  categoryId: undefined,
  departmentId: undefined,
  departmentPercentage: undefined,
  type: undefined,
  municipalServiceCode: undefined,
  registerDate: undefined,
  startDate: undefined,
  endDate: undefined,
  expectedPaymentDay: undefined,
  grossValue: undefined,
  netValue: undefined,
  discounts: undefined,
  taxAmount: undefined,
  taxes: {
    ir: undefined,
    pis: undefined,
    cofins: undefined,
    csll: undefined,
    icms: undefined,
    iss: undefined
  },
  status: undefined,
  billed: undefined,
  billingType: undefined,
  step: undefined,
  notes: undefined,
  createdAt: undefined,
  updatedAt: undefined
})
